met_range = (0,2000, True)


# title,    scale,  rebin, usrrng
settings = {
#    'h_htcheck':('', 1,1, (0,2000)),
#    'h_htbprimemass':('', None, None, None),
#    'h_ht_presel'           : ('H_{T} (GeV)', 10, 5, (1200,2000)),
#    'h_nfatjet_opt'          : ("AK8 jets multiplicity", 10, 1, None),
#    'h_nGoodPV'               : ("Number of Primary Vertices", 1000, 1, (0, 30)),
#    'h_nGoodPVw'           : ("Number of Primary Vertices", 1000, 1, (0, 30)),

#    'h_nPV'               : ("Number of Primary Vertices", 1000, 1, (0, 30)),
#    'h_nPV_w'           : ("Number of Primary Vertices", 1000, 1, (0, 30)),
    'h_deltaRbH'        : ("#DeltaR(b,H)", 100, 10, None),
    'h_AK4fwjets'      : ("AK4 forward jet multiplicity", 100, 1, (0, 10)),
    'h_AK4mult'        : ("AK4 jet multiplicity", 100, 1, (0,10)),
    'h_AK4mult aft'        : ("AK4 jet multiplicity", 100, 1, (0,10)),
    'h_AK4bmult'        : ("CSVv2M AK4 jet multiplicity", 100, 1, (0,5)),
    'h_AK8mult'        : ("AK8 jet multiplicity", 100, 1, (0,10)),
    'h_AK8mult aft'        : ("AK8 jet multiplicity", 100, 1, (0,10)),
    'h_AK4pt'        : ("AK4 jet p_{T} (GeV)", 100, 4, (30,500)),
    'h_AK4eta'        : ("AK4 jet #eta (GeV)", 100, 6, None),
    'h_AK4phi'        : ("AK4 jet #phi (GeV)", 100, 4, (-3.5, 3.5)),
    'h_AK4csv'        : ("AK4 jet CSVv2", 100, 2, None),
    'h_AK8pt'        : ("AK8 jet p_{T} (GeV)", 100, 4, (300,1500)),
    'h_AK8eta'        : ("AK8 jet #eta (GeV)", 100, 4, None),
    'h_AK8phi'        : ("AK8 jet #phi (GeV)", 100, 4, (-3.5, 3.5)),
    'h_nsubj'        : ("Number of subjets", 100, 1, None),
    'h_tau2tau1'       : ("N-subjetiness",100, 2, None),
    'h_prunedmass'       : ("AK8 pruned mass (GeV)", 100, 2,(0,300)),
    'h_Ht'                  : ('H_{T} (GeV)', 10, 20, (200,2500)),#
    'h_Ht_trigaft'                  : ('H_{T} (GeV)', 10, 10, (200,2500)),
    'h_Ht_trigbef'                  : ('H_{T} (GeV)', 10, 10, (200,2500)),
    'h_Ht_CRD'                  : ('H_{T} (GeV)', 10, 20, (200,2500)),
    'h_Ht_CRC'                  : ('H_{T} (GeV)', 10, 20, (200,2500)),
    'h_Ht_CRB'                  : ('H_{T} (GeV)', 10, 20, (200,2500)),
#    'h_Ht_trigbef'                  : ('H_{T} (GeV)', 10, 20, (600,2500)),
    'h_AK8_selh_pt_SR'        : ("Higgs-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK8_selh_eta_SR'        : ("Higgs-tagged jet #eta", 1, 4, None),
    'h_AK8_selh_phi_SR'        : ("Higgs-tagged jet #phi", 1, 4, (-3.5,3.5)),
    'h_AK4_selb_pt_SR'        : ("b-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK4_selb_eta_SR'        : ("b-tagged jet #eta", 1, 4, None),
    'h_AK4_selb_phi_SR'        : ("b-tagged jet #phi", 1, 4, (-3.5,3.5)),###

    'h_AK8_selh_pt_CRB'        : ("Higgs-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK8_selh_eta_CRB'        : ("Higgs-tagged jet #eta", 1, 4, None),
    'h_AK8_selh_phi_CRB'        : ("Higgs-tagged jet #phi", 1, 4, (-3.5,3.5)),
    'h_AK4_selb_pt_CRB'        : ("b-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK4_selb_eta_CRB'        : ("b-tagged jet #eta", 1, 4, None),
    'h_AK4_selb_phi_CRB'        : ("b-tagged jet #phi", 1, 4, (-3.5,3.5)),####
      'h_AK8_selh_pt_CRC'        : ("Higgs-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK8_selh_eta_CRC'        : ("Higgs-tagged jet #eta", 1, 4, None),
    'h_AK8_selh_phi_CRC'        : ("Higgs-tagged jet #phi", 1, 4, (-3.5,3.5)),
    'h_AK4_selb_pt_CRC'        : ("b-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK4_selb_eta_CRC'        : ("b-tagged jet #eta", 1, 4, None),
    'h_AK4_selb_phi_CRC'        : ("b-tagged jet #phi", 1, 4, (-3.5,3.5)),##

      'h_AK8_selh_pt_CRD'        : ("Higgs-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK8_selh_eta_CRD'        : ("Higgs-tagged jet #eta", 1, 4, None),
    'h_AK8_selh_phi_CRD'        : ("Higgs-tagged jet #phi", 1, 4, (-3.5,3.5)),
    'h_AK4_selb_pt_CRD'        : ("b-tagged jet p_{T} (GeV)", 1, 4, None),
    'h_AK4_selb_eta_CRD'        : ("b-tagged jet #eta", 1, 4, None),
    'h_AK4_selb_phi_CRD'        : ("b-tagged jet #phi", 1, 4, (-3.5,3.5)),##

    'h_bprimemass_SR'          : ("Reconstructed B' mass (GeV)", 10, 10, (400,2000)),
    'h_bprimemass_CRC'        : ("Reconstructed B' mass (GeV)", 10, 10, (400,2000)),
    'h_bprimemass_CRB'        : ("Reconstructed B' mass (GeV)", 10, 10, (400,2000)),
    'h_bprimemass_CRD'        : ("Reconstructed B' mass (GeV)", 10, 10, (400,2000)),

    'h_bprimept_SR'          : ("Reconstructed B' p_{T} (GeV)", 1, 4, None),
    'h_bprimept_CRC'        : ("Reconstructed B' p_{T} (GeV)", 1, 4, None),
    'h_bprimept_CRB'        : ("Reconstructed B' p_{T} (GeV)", 1, 4, None),
    'h_bprimept_CRD'        : ("Reconstructed B' p_{T} (GeV)", 1, 4, None),

    'h_bprimeeta_SR'          : ("Reconstructed B' #eta (GeV)", 1, 4, None),
    'h_bprimeeta_CRC'        : ("Reconstructed B' #eta (GeV)", 1, 4, None),
    'h_bprimeeta_CRB'        : ("Reconstructed B' #eta (GeV)", 1, 4, None),
    'h_bprimeeta_CRD'        : ("Reconstructed B' #eta (GeV)", 1, 4, None),

    'h_bprimephi_SR'          : ("Reconstructed B' #phi (GeV)", 1, 4, (-3.5,3.5)),
    'h_bprimephi_CRC'        : ("Reconstructed B' #phi (GeV)", 1, 4, (-3.5,3.5)),
    'h_bprimephi_CRB'        : ("Reconstructed B' #phi (GeV)", 1, 4, (-3.5,3.5)),
    'h_bprimephi_CRD'        : ("Reconstructed B' #phi (GeV)", 1, 4, (-3.5,3.5)),


#    'h_bprimept_SR'        : ("Reconstructed B' p_{T} (GeV)", 100, 2, None),
#    'h_bprimept_CRB'        : ("Reconstructed B' p_{T} (GeV)", 100, 2, None),
#    'h_bprimept_CRC'        : ("Reconstructed B' p_{T} (GeV)", 100, 2, None),
#    'h_bprimept_CRD'        : ("Reconstructed B' p_{T} (GeV)", 100, 2, None),

#    'h_bprimeeta_SR'        : ("Reconstructed B' #eta ", 100, 2, None),
#    'h_bprimeeta_CRB'        : ("Reconstructed B' #eta ", 100, 2, None),
#    'h_bprimeeta_CRC'        : ("Reconstructed B' #eta ", 100, 2, None),
#    'h_bprimeeta_CRD'        : ("Reconstructed B' #eta ", 100, 2, None),



    #    'h_ht_b'                  : ('H_{T} (GeV)', 10, 5, (200,2000)),
#    'h_ht_c'                  : ('H_{T} (GeV)', 10, 5, (200,2000)),
#    'h_ht_d'                  : ('H_{T} (GeV)', 10, 5, (200,2000)),
#    'h_ht_antib'            : ('H_{T} (GeV)', 10, 5, (1200,2000)),
#    'h_ht_santib'           : ('H_{T} (GeV)', 10, 5, (1200,2000)),
#    'h_ht_sb'               : ('H_{T} (GeV)', 10, 5, (1200,2000)),

#    'h_bprimemass_b'        : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemass_c'        : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemass_d'        : ('Mass (GeV)', 10, 2, None),

#    'h_ht_closure'          : ('H_{T} (GeV)', 10, 10, None),
#    'h_ht_antib_closure'    : ('H_{T} (GeV)', 10, 10, None),
#    'h_ht_santib_closure'   : ('H_{T} (GeV)', 10, 10, None),
#    'h_ht_sb_closure'       : ('H_{T} (GeV)', 10, 10, None),

#    'h_bprimemassbbreg1'          : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemassbbreg2'          : ('Mass (GeV)', 10, 2, None),

#    'h_bprimemassbbregm1'          : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemassnobbreg1'          : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemassnobbreg2'          : ('Mass (GeV)', 10, 2, None),
#    'h_bprimemassnobbregm1'          : ('Mass (GeV)', 10, 2, None),
    
#    'h_bprimemass_doubleb04'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_doubleb06'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_doubleb08'          : ('Mass (GeV)', 10, 4, None),

#    'h_bprimemass_a0'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_a1'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_a2'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_a3'          : ('Mass (GeV)', 10, 4, None),
    
#    'h_bprimemass_a'          : ('Mass (GeV)', 1, 4, None),
#    'h_bprimemass_b'          : ('Mass (GeV)', 1, 4, None),
#    'h_bprimemass_c'          : ('Mass (GeV)', 1, 4, None),
#    'h_bprimemass_d'          : ('Mass (GeV)', 1, 4, None),

#    'h_bprimemass_a_closure'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_b_closure'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_c_closure'          : ('Mass (GeV)', 10, 4, None),
#    'h_bprimemass_d_closure'          : ('Mass (GeV)', 10, 4, None),

#    'h_genfwqpt'            : ('p_{T} (GeV)', 10, 4, None),
#    'h_genfwqeta'           : ('#eta', 10, 5, None),
#    'h_genfwqphi'            : ('#phi', 10, 7, None),

#    'h_jetpt'               : ('p_{T} (GeV)', 10, 4, None),
#    'h_jeteta'              : ('#eta', 10, 5, None),
#    'h_jetphi'              : ('#phi', 10, 7, None),
#    'h_njet'                : ('AK4 jets multiplicity', 10, None, None),
    
#    'h_bjetpt'              : ('p_{T} (GeV)', 10, 4, None),
#    'h_bjeteta'             : ('#eta', 10, 5, None),
#    'h_bjetphi'             : ('#phi', 10, 7, None),
#    'h_nbjet'               : ('CVSM AK4 jets multiplicity', 10, None, None),

#    'h_nqcjet'              : ('forward jets multiplicity', 10, None, None),
#    'h_qcjetpt'            : ('p_{T} (GeV)', 10, 4, None),
#    'h_qcjeteta'           : ('#eta', 10, 5, None),

#    'h_deltaRb1'            : ("#DeltaR(reco b, gen b)", 10, 10, None),
#    'h_deltaRb2'            : ("#DeltaR(reco b, gen b)", 10, 10, None),
#    'h_matching'            : ("", 10, None, None),
#    'h_higgsjet_pt_a'   : ('p_{T} (GeV)', 10, 10, None),
#    'h_nhiggsjet_mass_presel' : ('Mass (GeV)',10, 10, None),
    
#    'h_nhiggsjet_nsubj_presel' : ('number of subjets', 10, 1, None),
#    'h_nhiggsjet_nsubj_a' : ('number of subjets', 10, 1,None),
#    'h_nhiggsjet_nsubj_b' : ('number of subjets', 10, 1,None),
#    'h_nhiggsjet_nsubj_c' : ('number of subjets', 10, 1,None),
#    'h_nhiggsjet_nsubj_d' : ('number of subjets', 10, 1,None),

#    'h_nhiggsjet_doubleB_presel'       : ('Double b-tag', 10, 1, None),
#    'h_nhiggsjet_doubleB_a'       : ('Double b-tag', 10, 1, None),
#    'h_nhiggsjet_doubleB_b'       : ('Double b-tag', 10, 1, None),
#    'h_nhiggsjet_doubleB_c'       : ('Double b-tag', 10, 1, None),
#    'h_nhiggsjet_doubleB_d'       : ('Double b-tag', 10, 1, None),
#    'h_fatjetpt'            : ('p_{T} (GeV)', 10, 4, None),
#    'h_fatjeteta'           : ('#eta', 10, 5, None),
#    'h_fatjetphi'           : ('#phi', 10, 7, None),
#    'h_nfatjet'             : ('AK8 jets multiplicity', 10, None, None),
#    'h_fatjetncsvmsubjets'  : ('CSVM subjets multiplicity', 10, None, None),
#    'h_fatjetprunedmass'    : ('pruned mass (GeV)', 10, None, None),
#    'h_fatjetnsubjetiness'  : ('#tau_{2}/#tau_{1}', 10, None, None),
#    'h_fatjetleadpt'        : ('Leading AK8 jet p_{T} (GeV)', 10, 4, None),
#    'h_fatjetsubleadpt'     : ('Sub-leading AK8 jet p_{T} (GeV)', 10, 4, None),

#    'h_higgspt'             : ('p_{T} (GeV)', 10, 4, None),
#    'h_higgseta'            : ('#eta', 10, 5, None),
#    'h_higgsphi'            : ('#phi', 10, 7, None),
#    'h_nhiggsjet'           : ('Higgs-tagged jets multiplicity', 10, None, None),#
#    'h_duobleb'             : ('double b-tagging cut', 10, 1, None),
    'h_cutFlow'             : ('', 10, None, None),
}


store = [
#    'h_htcheck',
 #   'h_htbprimemass',
#    'h_cutFlow',
#    'h_duobleb',
    'h_Ht_trigaft',
    'h_Ht_trigbef',
#    'h_HiggsmassVSnsubj_presel',
    'h_bprimemass_SR',
     'h_bprimemass_CRB',
     'h_bprimemass_CRD',
     'h_bprimemass_CRC',
        'h_Ht',
     'h_Ht_CRB',
     'h_Ht_CRD',
     'h_Ht_CRC',
    #    'h_bprimemass_doubleb06', 
#    'h_bprimemass_doubleb08',
#    'h_nhiggsjet_doubleB_presel',
#    'h_nhiggsjet_mass_presel',
#    'h_nhiggsjet_nsubj_presel',
#    'h_njet_opt',
##    'h_nfatjet_opt',
#    'h_ht_a',
#    'h_ht_b',
#    'h_ht_c',
#    'h_ht_d',
    #   'h_ht_antib',
 #   'h_ht_santib',
 #   'h_ht_sb',
 #   'h_ht_closure',
 #   'h_ht_antib_closure',
 #   'h_ht_santib_closure',
 #   'h_ht_sb_closure',
#    'h_bprimemass_a_closure',
#    'h_bprimemass_b_closure',
#    'h_bprimemass_c_closure',
#    'h_bprimemass_d_closure',
#    'h_bprimemass_a',
#    'h_bprimemass_a0',
#    'h_bprimemass_a1',
#    'h_bprimemass_a2',
#    'h_bprimemass_a3',
#    'h_bprimemass_b',
#    'h_bprimemass_c',
#    'h_bprimemass_d',
#    'met_preS',
#    'metFinal',
#    'metFinal_tag',
#    'metFinal_untag',
#    "metFinal_Angular",
#    "metFinal_Angular_tag",
#    "metFinal_Angular_untag",
]
